* emdwl - dwl for emacs

emdwl is the =dwl= binding of =emacs=.

You can start a =dwl= within =emacs= .

[[file:README_CN.org][简体中文]]

Functions achieved:

- Create window

- Move window

- resize window

- Show/hide Windows
  Move to another =tag=

** Compilation

Same as =dwl= : [[file:README.dwl.md][dwl_README]].

Use the following command:
#+begin_src shell :tangle no :shebang #!/bin/bash
  make emdwl #build so
  make test # Perform tests. Use alacritty
#+end_src

** Compilation dependency

=emdwl= required:
- wlroots
- wayland-protocols

=emdwl-tool= required:
- pos-tip

** Start

=emdwl= can be used directly by calling =emdwl-*=.

=emdl-tool= A simple combination of the necessary functions.

start an =emdwl= window with =./ emdl-start. sh=. This will open a window with minimal configuration as =daemon=.

#+begin_src emacs-lisp :tangle yes
  ;; Insert a test window into buffer (alacritty)
  (emdwl-tool-test-inline)
  ;; Enable window follow scrolling
  (emdwl-tool-add-advice)
  ;; Open a window "meld" to replace any window startup command
  (emdwl-tool-open "meld")
  ;; Insert a window into the current buffer
  (emdwl-tool-add-inline-client &optional client-id)
  ;; Adjust the window length and width
  (emdwl-resize x y height width client-id)
  ;; Close the window and clear the inserted window area
  (emdwl-tool-client-close client-id)
  ;; close emdwl
  (emdwl-close)
#+end_src

**  Acknowledgements

*emdwl* began by dwl began by extending the TinyWL example provided (CC0) by the sway/wlroots
developers. This was made possible in many cases by looking at how sway
accomplished something, then trying to do the same in as suckless a way as
possible.

Many thanks to suckless.org and the dwm developers and community for the
inspiration, and to the various contributors to the project, including:

- Alexander Courtis for the XWayland implementation
- Guido Cella for the layer-shell protocol implementation, patch maintenance,
  and for helping to keep the project running
- Stivvo for output management and fullscreen support, and patch maintenance
- dwl team for the dwl.

link:
+ [Wayland]: https://wayland.freedesktop.org/
+ [wlroots]: https://gitlab.freedesktop.org/wlroots/wlroots/
+ [dwl]: https://github.com/djpohly/dwl
+ [patches page on dwl wiki]: https://github.com/djpohly/dwl/wiki/Patches
